# Generated by Django 5.0.8 on 2026-01-10 20:50
# Drops the old cancellation fields on Order (replaced by the status field).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='canceled_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='canceled_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='by_user',
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='orderevent',
            name='type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name_snapshot',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_snapshot',
        ),
        migrations.AddField(
            model_name='orderevent',
            name='event',
            field=models.CharField(default='creates', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('PREP', 'En preparación'), ('READY', 'Listo'), ('CANCELED', 'Cancelado')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
