# Generated by Django 5.0.8 on 2026-01-14 19:06
# Adds the "zone" field to Order.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_order_canceled_at_remove_order_canceled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zone',
            field=models.CharField(default='Guaduas', max_length=60),
            preserve_default=False,
        ),
    ]
