# Generated by Django 5.2.1 on 2026-01-26 16:43
# Adds tip fields to Order: has_tip, tip_amount.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_order_is_paid_order_paid_at_order_paid_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_tip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tip_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
