# Generated by Django 5.2.1 on 2026-03-02 22:19
# Creates BusinessConfig, MenuCategory, Zone, Table, and links MenuItem to a category.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_order_has_tip_order_tip_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mi Restaurante', max_length=150, verbose_name='Nombre del negocio')),
                ('nit', models.CharField(blank=True, default='', max_length=50, verbose_name='NIT / ID fiscal')),
                ('address', models.CharField(blank=True, default='', max_length=250, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/', verbose_name='Logo')),
                ('tip_type', models.CharField(choices=[('NONE', 'Sin propina'), ('FIXED', 'Valor fijo'), ('PERCENT', 'Porcentaje')], default='FIXED', max_length=10, verbose_name='Tipo de propina')),
                ('tip_value', models.DecimalField(decimal_places=2, default=6000, help_text='Valor fijo en pesos o porcentaje (ej: 10 = 10%)', max_digits=10, verbose_name='Valor de propina')),
            ],
            options={
                'verbose_name': 'Configuración del negocio',
                'verbose_name_plural': 'Configuración del negocio',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría de menú',
                'verbose_name_plural': 'Categorías de menú',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, help_text='Para ordenar las zonas', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-available', 'category__order', 'name']},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='pos.menucategory', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número de mesa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='pos.zone')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['zone', 'number'],
                'unique_together': {('zone', 'number')},
            },
        ),
    ]
