# Generated by Django 5.2.1 on 2026-03-04 21:44
# Adds custom payment method display labels to BusinessConfig.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_businessconfig_menucategory_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='cash_label',
            field=models.CharField(default='Efectivo', max_length=40, verbose_name='Nombre Efectivo'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='nequi_label',
            field=models.CharField(default='Nequi', max_length=40, verbose_name='Nombre Nequi'),
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='transfer_label',
            field=models.CharField(default='Transferencia', max_length=40, verbose_name='Nombre Transferencia'),
        ),
    ]
